import type { BlockObjectRequest } from "@notionhq/client/build/src/api-endpoints.js";
import { FlowSyncClient } from "../notion-client.js";
import { blocks } from "../block-builder.js";
import { normalizeId } from "../util.js";
import { replacePageChildren } from "../upserts/common.js";
import { toMermaid } from "./mermaid.js";
import { type ArchGraph, LAYER_ORDER, LAYER_META } from "./types.js";

export interface ArchUpsertResult {
  pageId: string;
  created: boolean;
  url: string;
}

export class ArchUpserter {
  private readonly parentId: string;

  constructor(private readonly client: FlowSyncClient, parentPageId: string) {
    this.parentId = normalizeId(parentPageId);
  }

  async upsert(graph: ArchGraph): Promise<ArchUpsertResult> {
    const title = graph.title;
    const body = this.buildBody(graph);
    const existing = await this.findChildByTitle(title);

    if (existing) {
      await replacePageChildren(this.client, existing, body);
      const page = await this.client.withRetry(() =>
        this.client.notion.pages.retrieve({ page_id: existing })
      );
      return { pageId: existing, created: false, url: (page as { url: string }).url };
    }

    const created = await this.client.withRetry(() =>
      this.client.notion.pages.create({
        parent: { type: "page_id", page_id: this.parentId },
        properties: {
          title: { title: [{ type: "text", text: { content: title } }] }
        } as never,
        children: body
      })
    );
    return { pageId: created.id, created: true, url: (created as { url: string }).url };
  }

  private async findChildByTitle(title: string): Promise<string | null> {
    const res = await this.client.withRetry(() =>
      this.client.notion.search({
        query: title,
        filter: { property: "object", value: "page" },
        page_size: 20
      })
    );
    for (const r of res.results as Array<Record<string, unknown>>) {
      const parent = r.parent as { type?: string; page_id?: string } | undefined;
      if (parent?.type !== "page_id" || !parent.page_id) continue;
      if (normalizeId(parent.page_id) !== this.parentId) continue;
      if (this.plainTitle(r) === title) return r.id as string;
    }
    return null;
  }

  private plainTitle(page: Record<string, unknown>): string {
    const props = page.properties as Record<string, { type?: string; title?: Array<{ plain_text: string }> }> | undefined;
    if (!props) return "";
    for (const v of Object.values(props)) {
      if (v?.type === "title") return (v.title ?? []).map((t) => t.plain_text).join("");
    }
    return "";
  }

  private buildBody(graph: ArchGraph): BlockObjectRequest[] {
    const out: BlockObjectRequest[] = [];
    const now = new Date().toISOString().slice(0, 10);

    out.push(
      blocks.callout(
        `Auto-generated by FlowSync · ${now} · ${graph.nodes.length} components, ${graph.edges.length} links. Edit this diagram and run \`notion-sync arch scaffold\` to regenerate a prototype.`,
        "rocket"
      )
    );
    out.push(blocks.h2("System diagram"));
    out.push(blocks.code(toMermaid(graph), "mermaid"));
    out.push(blocks.divider());

    out.push(blocks.h2("Components"));
    for (const layer of LAYER_ORDER) {
      const nodes = graph.nodes.filter((n) => n.layer === layer);
      if (!nodes.length) continue;
      const m = LAYER_META[layer];
      out.push(
        blocks.toggle(
          `${m.emoji} ${layer} (${nodes.length})`,
          nodes.map((n) => {
            const deps = graph.edges
              .filter((e) => e.from === n.id)
              .map((e) => graph.nodes.find((x) => x.id === e.to)?.label ?? e.to);
            const tail = deps.length ? ` → depends on: ${deps.join(", ")}` : " → no internal deps";
            return blocks.bullet(`${n.emoji} ${n.label}${tail}`);
          })
        )
      );
    }

    out.push(blocks.divider());
    out.push(
      blocks.toggle("How to read this", [
        blocks.p("Each box is a deployable unit. Arrows are dependency direction (A → B means A imports/uses B)."),
        ...LAYER_ORDER.filter((l) => graph.nodes.some((n) => n.layer === l)).map((l) =>
          blocks.bullet(`${LAYER_META[l].emoji} ${l} — ${this.layerHint(l)}`)
        ),
        blocks.p("This page is bidirectional: regenerate it from code with `notion-sync arch push`, or draw a new diagram here and run `notion-sync arch scaffold` to get a code skeleton.")
      ])
    );

    return out;
  }

  private layerHint(layer: string): string {
    switch (layer) {
      case "Clients":
        return "entry points developers run (CLI, GitHub Action, dashboard)";
      case "Workers":
        return "serverless handlers (webhooks, agent tools)";
      case "Core":
        return "shared library every surface depends on";
      default:
        return "third-party systems FlowSync talks to";
    }
  }
}
