import { type ArchGraph, LAYER_META } from "./types.js";
import { toMermaid } from "./mermaid.js";

export interface ScaffoldFile {
  path: string; // relative to output root, POSIX separators
  contents: string;
}

export function planScaffold(graph: ArchGraph): ScaffoldFile[] {
  const files: ScaffoldFile[] = [];
  const slug = (s: string) =>
    s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "module";

  for (const node of graph.nodes) {
    const dir = slug(node.label);
    const deps = graph.edges
      .filter((e) => e.from === node.id)
      .map((e) => graph.nodes.find((x) => x.id === e.to))
      .filter(Boolean)
      .map((d) => ({ name: d!.label, dir: slug(d!.label) }));

    const exportName = node.label.replace(/^@[^/]+\//, "").replace(/[^a-zA-Z0-9]/g, "");
    const imports = deps
      .map((d) => `// import { ${d.name.replace(/[^a-zA-Z0-9]/g, "")} } from "../${d.dir}/index.js";`)
      .join("\n");

    files.push({
      path: `${dir}/index.ts`,
      contents: `${imports ? imports + "\n\n" : ""}/**
 * ${node.emoji} ${node.label}
 * Layer: ${node.layer}
 * Scaffolded by FlowSync from a Notion architecture diagram.
 */
export function ${exportName || "init"}() {
  throw new Error("${node.label}: not implemented — scaffolded stub");
}
`
    });

    files.push({
      path: `${dir}/README.md`,
      contents: `# ${node.emoji} ${node.label}

**Layer:** ${node.layer}

## Depends on
${deps.length ? deps.map((d) => `- \`${d.name}\` → \`../${d.dir}\``).join("\n") : "_No internal dependencies._"}

> Stub generated by \`notion-sync arch scaffold\` from the Notion diagram.
`
    });
  }

  files.push({
    path: "ARCHITECTURE.md",
    contents: `# ${graph.title}

Scaffolded from a Notion architecture diagram by FlowSync.

\`\`\`mermaid
${toMermaid(graph)}
\`\`\`

## Layers
${[...new Set(graph.nodes.map((n) => n.layer))]
  .map((l) => `- ${LAYER_META[l as keyof typeof LAYER_META]?.emoji ?? "🔹"} **${l}**`)
  .join("\n")}

## Modules
${graph.nodes.map((n) => `- ${n.emoji} \`${n.label}\``).join("\n")}
`
  });

  files.push({
    path: "flowsync.arch.json",
    contents: JSON.stringify(graph, null, 2)
  });

  return files;
}
